name: KL6003
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - jupyterlab
  - ipywidgets
  - nglview
  - spglib
  - ase
  - gpaw
  - gpaw-data
  - pip
  - pip:
    - mace-torch
